plugins {
    id 'java'
    id 'org.springframework.boot' version '3.3.4'
    id 'io.spring.dependency-management' version '1.1.6'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {


    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    compileOnly 'org.projectlombok:lombok'
    implementation 'com.h2database:h2'
//    runtimeOnly 'mysql:mysql-connector-java:8.0.29'
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    testCompileOnly 'org.projectlombok:lombok'
    testAnnotationProcessor 'org.projectlombok:lombok'
    implementation 'com.github.gavlyukovskiy:p6spy-spring-boot-starter:1.9.0'


    // P6Spy 의존성 추가
    implementation 'com.github.gavlyukovskiy:p6spy-spring-boot-starter:1.9.0'

//    // 모니터링을 위해 액츄에이터
//    implementation 'org.springframework.boot:spring-boot-starter-actuator'
//    // 프로메테우스
//    implementation 'io.micrometer:micrometer-registry-prometheus'

}


tasks.named('test') {
    useJUnitPlatform()
}
