spring:
  application:
    name: VisitDestinationReview
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password: ''
#    hikari:
#      maximum-pool-size: 100
#      connection-timeout: 5000
#      connection-init-sql: SELECT 1
#      validation-timeout: 2000
#      minimum-idle: 10
#      idle-timeout: 600000
#      max-lifetime: 1800000

  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true




